name: Deploy to upload.dance-offs.com

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete sync state on server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.fasthosts.co.uk
          username: upload.dance-offs.com
          password: ${{ secrets.FTP_PASSWORD_UPLOAD }}
          local-dir: ./empty-dir/
          server-dir: /htdocs/
          dangerous-clean-slate: true

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.fasthosts.co.uk
          username: upload.dance-offs.com
          password: ${{ secrets.FTP_PASSWORD_UPLOAD }}
          local-dir: ./
          server-dir: /htdocs/
          protocol: ftp
          log-level: verbose
