name: Deploy to Fasthosts via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload to Fasthosts via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}       # ftp.fasthosts.co.uk
          username: ${{ secrets.FTP_USERNAME }} # bazwahh
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: htdocs/
          protocol: ftps
          port: 21
          security: strict
